services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_VER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    labels:
      - "traefik.http.routers.portainer.rule=PathPrefix(`/portainer/`)"
      - "traefik.http.routers.portainer.middlewares=https-redirect"
      - "traefik.http.routers.portainer-secure.tls=true"
      - "traefik.http.routers.portainer-secure.rule=PathPrefix(`/portainer/`)"
      - "traefik.http.routers.portainer-secure.middlewares=portainer-stripprefix"
      - "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer/"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    restart: always

  traefik:
    container_name: traefik
    image: traefik:${TRAEFIK_VER}
    command:
      - --providers.docker=true 
      - --serversTransport.insecureSkipVerify=true
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=https-redirect"
      - "traefik.http.routers.api-secure.tls=true"
      - "traefik.http.routers.api-secure.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
    restart: always

volumes:
  portainer: