services:
  splunk:
    container_name: splunk
    image: splunk/splunk:${SPLUNK_VER}
    ports:
      - 9997:9997
      - 8089:8089
      - 8000:8000
    environment:
      SPLUNK_PASSWORD: $SPLUNK_PASSWORD
      SPLUNK_START_ARGS: '--accept-license'
      #SPLUNK_UPGRADE: 'true' # Only use when upgrading splunk. Modify SPLUNK_VER in .env to the version you want
    volumes:
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var
      - ./web.conf:/opt/splunk/etc/system/local/web.conf
      - ../zeek/zeek-logs/:/logs/zeek-logs/
    labels:
    restart: unless-stopped

volumes:
  splunk_etc:
  splunk_var:
