services:
    zeek:
        container_name: zeek
        image: blacktop/zeek:latest
        restart: always
        network_mode: host
        cap_add:
          - NET_RAW
        volumes:
          - ./zeek-logs/:/pcap:rw
          - ./__load__.zeek:/usr/local/zeek/share/zeek/base/bif/__load__.zeek
        command:
          - -i ${INTERFACE} -C